# pubspec.yaml - FIXED VERSION
name: thieu_nhi_app
description: Ứng dụng quản lý thiếu nhi Giáo xứ Thiên Ân
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.5
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Utils
  excel: ^2.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1     
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Development
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  disable-swift-package-manager: true
  
  assets:
    - .env
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

# THÊM CONFIGURATION CHO NATIVE SPLASH
flutter_native_splash:
  # Logo của bạn (màu đầy đủ)
  image: assets/images/logo.png
  
  # Background color - neutral để logo colorful nổi bật
  color: "F8F9FA"  # Trắng xám rất nhạt
  
  # Tự động tạo splash cho Android và iOS
  android: true
  ios: true
  web: false
  
  # Thời gian hiển thị tối thiểu (optional)
  android_gravity: center
  ios_content_mode: center
  
  # Fullscreen splash
  fullscreen: true
  
  # Adaptive cho Android 12+
  android_12:
    image: assets/images/logo.png
    color: "F8F9FA"
    icon_background_color: "FFFFFF"